server:
  port: 31000

spring:
  application:
    name: gulimall-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  redis:
    host: 169.254.37.10
    port: 6379

  thymeleaf:
    cache: false

  session:
    store-type: redis
    timeout: 30m



