server:
  port: 31000

spring:
  application:
    name: gulimall-auth-service
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.107.138:8848

  redis:
    host: 1.15.107.138
    port: 6379

  thymeleaf:
    cache: false

  session:
    store-type: redis
    timeout: 30m



