server:
  port: 9000

spring:
  application:
    name: gulimall-order
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.107.138:8848
  datasource:
    url: jdbc:mysql://1.15.107.138:3306/gulimall-oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: cb123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  # sql\u6620\u5C04\u6587\u4EF6
  mapper-locations: classpath:/mapper/**/*.xml
  # \u4E3B\u952E\u81EA\u589E
  global-config:
    db-config:
      id-type: auto