server:
  port: 12000
spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.107.138:8848
  thymeleaf:
    cache: false
  redis:
    host: 1.15.107.138
    port: 6379
  session:
      store-type: redis
