#server:
#  port: 40000
#
#spring:
#  application:
#    name: gulimall-cart
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
##        ip: 169.254.37.238
#  thymeleaf:
#    cache: false
#  redis:
#    host: 169.254.37.10
#    port: 6379
#  session:
#    store-type: redis
#    timeout: 30m
#
#thread:
#  minSize: 20
#  maxSize: 200
#  aliveTime: 10
#
#
